#  Copyright Â© Microsoft Corporation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  namespace: osdu
spec:
  replicas: {{ .Values.global.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
        aadpodidbinding: osdu-identity
    spec:
      volumes:
      - name: azure-keyvault
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: azure-keyvault
      containers:
      - name: {{ .Release.Name }}-{{ .Chart.Name }}
        image: {{ .Values.image.repository }}/{{ .Chart.Name }}-{{ .Values.global.image.branch }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.service.port }}
        readinessProbe:
          httpGet:
            path: {{ .Values.service.probe.path }}
            port: {{ .Values.service.port }}
        volumeMounts:
        - name: azure-keyvault
          mountPath: "/mnt/azure-keyvault"
          readOnly: true
        env:
        - name: spring_application_name
          value: storage
        - name: server.servlet.contextPath
          value: /api/storage/v2/
        - name: server_port
          value: "80"
        - name: ACCEPT_HTTP  # TEMPORARY UNTIL HTTPS
          value: "true"
        - name: KEYVAULT_URI
          valueFrom:
            configMapKeyRef:
              name: osdu-svc-properties
              key: ENV_KEYVAULT
        - name: AZURE_TENANT_ID
          valueFrom:
            configMapKeyRef:
              name: osdu-svc-properties
              key: ENV_TENANT_ID
        - name: AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: clientid
              key: clientid
        - name: AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: clientpassword
              key: clientpassword
        - name: aad_client_id
          valueFrom:
            secretKeyRef:
              name: appid
              key: appid
        - name: azure_activedirectory_session_stateless
          value: "true"
        - name: azure_activedirectory_AppIdUri
          value: "api://$(aad_client_id)"
        - name: appinsights_key
          valueFrom:
            secretKeyRef:
              name: appinsights
              key: appinsights
        - name: cosmosdb_account
          valueFrom:
            configMapKeyRef:
              name: osdu-svc-properties
              key: ENV_COSMOSDB_HOST
        - name: cosmosdb_key
          valueFrom:
            secretKeyRef:
              name: cosmos
              key: cosmos
        - name: cosmosdb_database
          value: osdu-db
        - name: servicebus_namespace_name
          valueFrom:
            configMapKeyRef:
              name: osdu-svc-properties
              key: ENV_SERVICEBUS_NAMESPACE
        - name: servicebus_connection_string
          valueFrom:
            secretKeyRef:
              name: servicebus
              key: servicebus
        - name: servicebus_topic_name
          value: recordstopic
        - name: storage_account
          valueFrom:
            configMapKeyRef:
              name: osdu-svc-properties
              key: ENV_STORAGE_ACCOUNT
        - name: storage_account_key
          valueFrom:
            secretKeyRef:
              name: storage
              key: storage
        - name: entitlements_service_endpoint
          value: http://entitlements-azure/entitlements/v1
        - name: entitlements_service_api_key
          value: "OBSOLETE"
        - name: legal_service_endpoint
          value: http://legal/api/legal/v1
        - name: legal_service_region
          value: southcentralus
        - name: search_service_endpoint
          value: http://legal/api/legal/v1

