# Required Group Variables - `Infrastructure Pipeline Variables`
  # AGENT_POOL
  # BUILD_ARTIFACT_NAME
  # SERVICE_CONNECTION_NAME
  # TF_VAR_remote_state_account
  # TF_VAR_remote_state_container

# Required Group Variables - `Infrastructure Pipeline - {env_name}`
  # TF_VAR_aks_agent_vm_count
  # ARM_SUBSCRIPTION_ID
  # TF_VAR_aks_agent_vm_count
  # TF_VAR_cosmosdb_replica_location
  # TF_VAR_data_sources_workspace_name
  # TF_VAR_flux_recreate
  # TF_VAR_gitops_path
  # TF_VAR_gitops_ssh_url
  # TF_VAR_gitops_url_branch
  # TF_VAR_image_repository_workspace_name
  # TF_VAR_resource_group_location

# Required Env Group Variables - `Infrastructure Pipeline Secrets - {env_name}` (for each {env_name})
  # elastic-username-ado-{env_name}
  # elastic-password-ado-{env_name}
  # elastic-endpoint-ado-{env_name}

# Deploy and validate infra changes once changes have been merged into
trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - /devops/infrastructure/*
    - /infra/modules/providers/*
    - /infra/templates/az-micro-svc-small-elastic-cloud/*
    - /test-harness/terratest-extensions/*
    exclude:
    - /**/*.md

variables:
- name: 'TF_VERSION'
  value: '0.12.20'
- name: 'GO_VERSION'
  value: '1.12.14'
- name: 'TF_ROOT_DIR'
  value: 'infra'
- name: 'PIPELINE_ROOT_DIR'
  value: 'devops/infrastructure'
- name: 'TEST_HARNESS_DIR'
  value: 'test-harness'
- group: 'Infrastructure Pipeline Variables'

stages:
- template: prepare-stage.yml
  parameters:
    environments:
    - name: 'devint'
      enablePrIsolation: false
      resourceNameIsolationLevel: 8
    - name: 'qa'
      enablePrIsolation: false
      resourceNameIsolationLevel: 8
    - name: 'prod'
      enablePrIsolation: false
      resourceNameIsolationLevel: 8

    configurations:
    - jobName: osdu_r2
      terraformWorkspacePrefix: ADO
      terraformTemplatePath: infra/templates/osdu-r2-resources
      deploymentTimeoutInMinutes: 120  # Not supported as a Variable :-(
